# Generated by Django 3.2.6 on 2022-06-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('idno', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('mname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('sex', models.CharField(choices=[('ወንድ', 'ወንድ'), ('ሴት', 'ሴት')], max_length=10, null=True)),
                ('bday', models.DateField(blank=True, null=True)),
                ('midb', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('wereda', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=100, null=True)),
                ('fam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fam_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('dikuna', models.CharField(blank=True, choices=[('-ዲያቆን', '-ዲያቆን'), ('እጩ ዲያቆን', 'እጩ ዲያቆን')], max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, default='/images/logo.jpg', null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
