# Generated by Django 4.1 on 2022-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_alter_child_midb_alter_course_lemidb_alter_mark_midb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='dikuna',
            field=models.CharField(blank=True, choices=[('-ዲያቆን', '-ዲያቆን'), ('እጩ ዲያቆን', 'እጩ ዲያቆን')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='midb',
            field=models.CharField(blank=True, choices=[('ወጣት', 'ወጣት'), ('ቤተ ዮሐንስ', 'ቤተ ዮሐንስ'), ('ቤተ አረጋዊ', 'ቤተ አረጋዊ'), ('ቤተ መድኃኔአለም', 'ቤተ መድኃኔአለም'), ('ቤተ ኪዳነምህረት', 'ቤተ ኪዳነምህረት')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lemidb',
            field=models.CharField(choices=[('ቤተ ዮሐንስ', 'ቤተ ዮሐንስ'), ('ቤተ መድኃኔአለም', 'ቤተ መድኃኔአለም'), ('ቤተ አረጋዊ', 'ቤተ አረጋዊ'), ('ቤተ ኪዳነምህረት', 'ቤተ ኪዳነምህረት')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='midb',
            field=models.CharField(blank=True, choices=[('ቤተ ዮሐንስ', 'ቤተ ዮሐንስ'), ('ቤተ መድኃኔአለም', 'ቤተ መድኃኔአለም'), ('ቤተ አረጋዊ', 'ቤተ አረጋዊ'), ('ቤተ ኪዳነምህረት', 'ቤተ ኪዳነምህረት')], max_length=100, null=True),
        ),
    ]
