# Generated by Django 3.2.6 on 2022-06-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ማይሰራ ነገር', 'ማይሰራ ነገር'), ('መዳረሻ ገጽ ጭማሪ ጥያቄ', 'መዳረሻ ገጽ ጭማሪ ጥያቄ'), ('መስተካከል ያለበት', 'መስተካከል ያለበት'), ('መጨመር ያለበት', 'መጨመር ያለበት'), ('አስተያየት', 'አስተያየት')], max_length=100, null=True)),
                ('comment', models.CharField(max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('contact', models.CharField(blank=True, max_length=1000)),
                ('criticality', models.CharField(blank=True, choices=[('አስቸኩይ', 'አስቸኩይ'), ('መካከለኛ', 'መካከለኛ'), ('ማያስቸኩል', 'ማያስቸኩል')], max_length=1000)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GodFather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('debr', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_no', models.CharField(max_length=100, null=True, unique=True)),
                ('property_name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('ንዋየ ቅድሳት', 'ንዋየ ቅድሳት'), ('የድግስ እቃዎች', 'የድግስ እቃዎች'), ('ምግብ ነክ ቁሶች', 'ምግብ ነክ ቁሶች'), ('የጽህፈት መሳሪያቆች', 'የጽህፈት መሳሪያቆች'), ('የኤሌክትሮኒክስ የአይቲ እቃዎች', 'የኤሌክትሮኒክስ/የአይቲ እቃዎች'), ('የቢሮ እቃዎች', 'የቢሮ እቃዎች')], max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('አላቂ', 'አላቂ'), ('ቆሚ', 'ቆሚ')], max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_mesnt', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(choices=[('አዲስ', 'አዲስ'), ('አሮጌ', 'አሮጌ'), ('ያገለገለ', 'ያገለገለ'), ('የሚወገድ', 'የሚወገድ')], max_length=100, null=True)),
                ('purch_date', models.DateField(blank=True)),
                ('exp_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.CharField(max_length=100, null=True, unique=True)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('mname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('ሴት', 'ሴት'), ('ወንድ', 'ወንድ')], max_length=10, null=True)),
                ('bday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ያላገባ', 'ያላገባ'), ('ያገባ', 'ያገባ')], max_length=50, null=True)),
                ('rid_no', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('wereda', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sos_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sos_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=300, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('talent', models.CharField(blank=True, max_length=500, null=True)),
                ('activity', models.CharField(choices=[('ያገለግላሉ', 'ያገለግላሉ'), ('አያገለግሉም', 'አያገለግሉም')], max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('kifl', models.CharField(blank=True, choices=[('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል')], max_length=500, null=True)),
                ('dikuna', models.CharField(blank=True, choices=[('እጩ ቀሲስ', 'እጩ ቀሲስ'), ('-ዲያቆን', '-ዲያቆን'), ('እጩ ዲያቆን', 'እጩ ዲያቆን'), ('-ቀሲስ', '-ቀሲስ')], max_length=50, null=True)),
                ('zemari', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, default='/images/logo.jpg', null=True, upload_to='media')),
                ('c_father_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='membermgmt.godfather')),
            ],
        ),
        migrations.CreateModel(
            name='Fekad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kifl', models.CharField(blank=True, choices=[('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል')], max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('request_date', models.DateField(auto_now_add=True, null=True)),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('approval', models.CharField(choices=[('ጸድቁአል', 'ጸድቁአል'), ('ተጠይቁአል', 'ተጠይቁአል'), ('አልጸደቀም', 'አልጸደቀም')], default='ተጠይቁአል', max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membermgmt.members')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.CharField(max_length=100, null=True, unique=True)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('mname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('ሴት', 'ሴት'), ('ወንድ', 'ወንድ')], max_length=10, null=True)),
                ('bday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ያላገባ', 'ያላገባ'), ('ያገባ', 'ያገባ')], max_length=50, null=True)),
                ('rid_no', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('wereda', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sos_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sos_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('current_class', models.CharField(choices=[('ቀዳማይ', 'ቀዳማይ'), ('ሣልሣይ', 'ሣልሣይ'), ('ራብዓይ', 'ራብዓይ'), ('ካልዓይ', 'ካልዓይ')], max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, default='/images/logo.jpg', null=True, upload_to='media')),
                ('n_father_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membermgmt.godfather')),
            ],
        ),
    ]
