# Generated by Django 3.2.6 on 2022-06-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membermgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='criticality',
            field=models.CharField(blank=True, choices=[('አስቸኩይ', 'አስቸኩይ'), ('ማያስቸኩል', 'ማያስቸኩል'), ('መካከለኛ', 'መካከለኛ')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('መጨመር ያለበት', 'መጨመር ያለበት'), ('መዳረሻ ገጽ ጭማሪ ጥያቄ', 'መዳረሻ ገጽ ጭማሪ ጥያቄ'), ('ማይሰራ ነገር', 'ማይሰራ ነገር'), ('አስተያየት', 'አስተያየት'), ('መስተካከል ያለበት', 'መስተካከል ያለበት')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_class',
            field=models.CharField(choices=[('ካልዓይ', 'ካልዓይ'), ('ሣልሣይ', 'ሣልሣይ'), ('ቀዳማይ', 'ቀዳማይ'), ('ራብዓይ', 'ራብዓይ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('ያገባ', 'ያገባ'), ('ያላገባ', 'ያላገባ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='approval',
            field=models.CharField(choices=[('አልጸደቀም', 'አልጸደቀም'), ('ጸድቁአል', 'ጸድቁአል'), ('ተጠይቁአል', 'ተጠይቁአል')], default='ተጠይቁአል', max_length=50),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='kifl',
            field=models.CharField(blank=True, choices=[('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='activity',
            field=models.CharField(choices=[('አያገለግሉም', 'አያገለግሉም'), ('ያገለግላሉ', 'ያገለግላሉ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='dikuna',
            field=models.CharField(blank=True, choices=[('-ዲያቆን', '-ዲያቆን'), ('እጩ ቀሲስ', 'እጩ ቀሲስ'), ('-ቀሲስ', '-ቀሲስ'), ('እጩ ዲያቆን', 'እጩ ዲያቆን')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='kifl',
            field=models.CharField(blank=True, choices=[('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('ያገባ', 'ያገባ'), ('ያላገባ', 'ያላገባ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('የጽህፈት መሳሪያቆች', 'የጽህፈት መሳሪያቆች'), ('ምግብ ነክ ቁሶች', 'ምግብ ነክ ቁሶች'), ('የኤሌክትሮኒክስ የአይቲ እቃዎች', 'የኤሌክትሮኒክስ/የአይቲ እቃዎች'), ('የቢሮ እቃዎች', 'የቢሮ እቃዎች'), ('ንዋየ ቅድሳት', 'ንዋየ ቅድሳት'), ('የድግስ እቃዎች', 'የድግስ እቃዎች')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('አሮጌ', 'አሮጌ'), ('አዲስ', 'አዲስ'), ('የሚወገድ', 'የሚወገድ'), ('ያገለገለ', 'ያገለገለ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('ቆሚ', 'ቆሚ'), ('አላቂ', 'አላቂ')], max_length=100, null=True),
        ),
    ]
