# Generated by Django 3.2.6 on 2022-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membermgmt', '0002_auto_20220604_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('ማይሰራ ነገር', 'ማይሰራ ነገር'), ('መጨመር ያለበት', 'መጨመር ያለበት'), ('አስተያየት', 'አስተያየት'), ('መስተካከል ያለበት', 'መስተካከል ያለበት'), ('መዳረሻ ገጽ ጭማሪ ጥያቄ', 'መዳረሻ ገጽ ጭማሪ ጥያቄ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_class',
            field=models.CharField(choices=[('ሣልሣይ', 'ሣልሣይ'), ('ካልዓይ', 'ካልዓይ'), ('ራብዓይ', 'ራብዓይ'), ('ቀዳማይ', 'ቀዳማይ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='sex',
            field=models.CharField(choices=[('ወንድ', 'ወንድ'), ('ሴት', 'ሴት')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('ያላገባ', 'ያላገባ'), ('ያገባ', 'ያገባ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='approval',
            field=models.CharField(choices=[('ተጠይቁአል', 'ተጠይቁአል'), ('አልጸደቀም', 'አልጸደቀም'), ('ጸድቁአል', 'ጸድቁአል')], default='ተጠይቁአል', max_length=50),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='kifl',
            field=models.CharField(blank=True, choices=[('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='activity',
            field=models.CharField(choices=[('ያገለግላሉ', 'ያገለግላሉ'), ('አያገለግሉም', 'አያገለግሉም')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='dikuna',
            field=models.CharField(blank=True, choices=[('እጩ ዲያቆን', 'እጩ ዲያቆን'), ('-ቀሲስ', '-ቀሲስ'), ('እጩ ቀሲስ', 'እጩ ቀሲስ'), ('-ዲያቆን', '-ዲያቆን')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='kifl',
            field=models.CharField(blank=True, choices=[('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='sex',
            field=models.CharField(choices=[('ወንድ', 'ወንድ'), ('ሴት', 'ሴት')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('ያላገባ', 'ያላገባ'), ('ያገባ', 'ያገባ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('የቢሮ እቃዎች', 'የቢሮ እቃዎች'), ('ንዋየ ቅድሳት', 'ንዋየ ቅድሳት'), ('የኤሌክትሮኒክስ የአይቲ እቃዎች', 'የኤሌክትሮኒክስ/የአይቲ እቃዎች'), ('የጽህፈት መሳሪያቆች', 'የጽህፈት መሳሪያቆች'), ('የድግስ እቃዎች', 'የድግስ እቃዎች'), ('ምግብ ነክ ቁሶች', 'ምግብ ነክ ቁሶች')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('ያገለገለ', 'ያገለገለ'), ('አዲስ', 'አዲስ'), ('የሚወገድ', 'የሚወገድ'), ('አሮጌ', 'አሮጌ')], max_length=100, null=True),
        ),
    ]
