# Generated by Django 3.2.6 on 2022-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membermgmt', '0003_auto_20220604_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='criticality',
            field=models.CharField(blank=True, choices=[('መካከለኛ', 'መካከለኛ'), ('አስቸኩይ', 'አስቸኩይ'), ('ማያስቸኩል', 'ማያስቸኩል')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('አስተያየት', 'አስተያየት'), ('መዳረሻ ገጽ ጭማሪ ጥያቄ', 'መዳረሻ ገጽ ጭማሪ ጥያቄ'), ('ማይሰራ ነገር', 'ማይሰራ ነገር'), ('መጨመር ያለበት', 'መጨመር ያለበት'), ('መስተካከል ያለበት', 'መስተካከል ያለበት')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_class',
            field=models.CharField(choices=[('ሣልሣይ', 'ሣልሣይ'), ('ራብዓይ', 'ራብዓይ'), ('ቀዳማይ', 'ቀዳማይ'), ('ካልዓይ', 'ካልዓይ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='sex',
            field=models.CharField(choices=[('ሴት', 'ሴት'), ('ወንድ', 'ወንድ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='approval',
            field=models.CharField(choices=[('ጸድቁአል', 'ጸድቁአል'), ('ተጠይቁአል', 'ተጠይቁአል'), ('አልጸደቀም', 'አልጸደቀም')], default='ተጠይቁአል', max_length=50),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='kifl',
            field=models.CharField(blank=True, choices=[('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='dikuna',
            field=models.CharField(blank=True, choices=[('-ቀሲስ', '-ቀሲስ'), ('እጩ ዲያቆን', 'እጩ ዲያቆን'), ('እጩ ቀሲስ', 'እጩ ቀሲስ'), ('-ዲያቆን', '-ዲያቆን')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='kifl',
            field=models.CharField(blank=True, choices=[('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='sex',
            field=models.CharField(choices=[('ሴት', 'ሴት'), ('ወንድ', 'ወንድ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('ንዋየ ቅድሳት', 'ንዋየ ቅድሳት'), ('የቢሮ እቃዎች', 'የቢሮ እቃዎች'), ('ምግብ ነክ ቁሶች', 'ምግብ ነክ ቁሶች'), ('የጽህፈት መሳሪያቆች', 'የጽህፈት መሳሪያቆች'), ('የድግስ እቃዎች', 'የድግስ እቃዎች'), ('የኤሌክትሮኒክስ የአይቲ እቃዎች', 'የኤሌክትሮኒክስ/የአይቲ እቃዎች')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('አሮጌ', 'አሮጌ'), ('ያገለገለ', 'ያገለገለ'), ('አዲስ', 'አዲስ'), ('የሚወገድ', 'የሚወገድ')], max_length=100, null=True),
        ),
    ]
