# Generated by Django 3.2.6 on 2022-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membermgmt', '0004_auto_20220606_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='criticality',
            field=models.CharField(blank=True, choices=[('አስቸኩይ', 'አስቸኩይ'), ('መካከለኛ', 'መካከለኛ'), ('ማያስቸኩል', 'ማያስቸኩል')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('ማይሰራ ነገር', 'ማይሰራ ነገር'), ('መስተካከል ያለበት', 'መስተካከል ያለበት'), ('መዳረሻ ገጽ ጭማሪ ጥያቄ', 'መዳረሻ ገጽ ጭማሪ ጥያቄ'), ('መጨመር ያለበት', 'መጨመር ያለበት'), ('አስተያየት', 'አስተያየት')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_class',
            field=models.CharField(choices=[('ሣልሣይ', 'ሣልሣይ'), ('ቀዳማይ', 'ቀዳማይ'), ('ራብዓይ', 'ራብዓይ'), ('ካልዓይ', 'ካልዓይ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='sex',
            field=models.CharField(choices=[('ወንድ', 'ወንድ'), ('ሴት', 'ሴት')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='approval',
            field=models.CharField(choices=[('ጸድቁአል', 'ጸድቁአል'), ('አልጸደቀም', 'አልጸደቀም'), ('ተጠይቁአል', 'ተጠይቁአል')], default='ተጠይቁአል', max_length=50),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='kifl',
            field=models.CharField(blank=True, choices=[('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='dikuna',
            field=models.CharField(blank=True, choices=[('እጩ ዲያቆን', 'እጩ ዲያቆን'), ('-ቀሲስ', '-ቀሲስ'), ('እጩ ቀሲስ', 'እጩ ቀሲስ'), ('-ዲያቆን', '-ዲያቆን')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='kifl',
            field=models.CharField(blank=True, choices=[('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='sex',
            field=models.CharField(choices=[('ወንድ', 'ወንድ'), ('ሴት', 'ሴት')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('የቢሮ እቃዎች', 'የቢሮ እቃዎች'), ('ምግብ ነክ ቁሶች', 'ምግብ ነክ ቁሶች'), ('የኤሌክትሮኒክስ የአይቲ እቃዎች', 'የኤሌክትሮኒክስ/የአይቲ እቃዎች'), ('የጽህፈት መሳሪያቆች', 'የጽህፈት መሳሪያቆች'), ('የድግስ እቃዎች', 'የድግስ እቃዎች'), ('ንዋየ ቅድሳት', 'ንዋየ ቅድሳት')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('የሚወገድ', 'የሚወገድ'), ('አዲስ', 'አዲስ'), ('ያገለገለ', 'ያገለገለ'), ('አሮጌ', 'አሮጌ')], max_length=100, null=True),
        ),
    ]
