# Generated by Django 3.2.6 on 2022-06-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membermgmt', '0006_auto_20220607_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='criticality',
            field=models.CharField(blank=True, choices=[('አስቸኩይ', 'አስቸኩይ'), ('መካከለኛ', 'መካከለኛ'), ('ማያስቸኩል', 'ማያስቸኩል')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('አስተያየት', 'አስተያየት'), ('መዳረሻ ገጽ ጭማሪ ጥያቄ', 'መዳረሻ ገጽ ጭማሪ ጥያቄ'), ('መስተካከል ያለበት', 'መስተካከል ያለበት'), ('ማይሰራ ነገር', 'ማይሰራ ነገር'), ('መጨመር ያለበት', 'መጨመር ያለበት')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_class',
            field=models.CharField(choices=[('ራብዓይ', 'ራብዓይ'), ('ሣልሣይ', 'ሣልሣይ'), ('ቀዳማይ', 'ቀዳማይ'), ('ካልዓይ', 'ካልዓይ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('ያገባ', 'ያገባ'), ('ያላገባ', 'ያላገባ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='approval',
            field=models.CharField(choices=[('ተጠይቁአል', 'ተጠይቁአል'), ('ጸድቁአል', 'ጸድቁአል'), ('አልጸደቀም', 'አልጸደቀም')], default='ተጠይቁአል', max_length=50),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='kifl',
            field=models.CharField(blank=True, choices=[('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='activity',
            field=models.CharField(choices=[('ያገለግላሉ', 'ያገለግላሉ'), ('አያገለግሉም', 'አያገለግሉም')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='dikuna',
            field=models.CharField(blank=True, choices=[('እጩ ቀሲስ', 'እጩ ቀሲስ'), ('እጩ ዲያቆን', 'እጩ ዲያቆን'), ('-ዲያቆን', '-ዲያቆን'), ('-ቀሲስ', '-ቀሲስ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='kifl',
            field=models.CharField(blank=True, choices=[('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('ያገባ', 'ያገባ'), ('ያላገባ', 'ያላገባ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('የኤሌክትሮኒክስ የአይቲ እቃዎች', 'የኤሌክትሮኒክስ/የአይቲ እቃዎች'), ('የጽህፈት መሳሪያቆች', 'የጽህፈት መሳሪያቆች'), ('የድግስ እቃዎች', 'የድግስ እቃዎች'), ('የቢሮ እቃዎች', 'የቢሮ እቃዎች'), ('ንዋየ ቅድሳት', 'ንዋየ ቅድሳት'), ('ምግብ ነክ ቁሶች', 'ምግብ ነክ ቁሶች')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('የሚወገድ', 'የሚወገድ'), ('አዲስ', 'አዲስ'), ('አሮጌ', 'አሮጌ'), ('ያገለገለ', 'ያገለገለ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('ቆሚ', 'ቆሚ'), ('አላቂ', 'አላቂ')], max_length=100, null=True),
        ),
    ]
