# Generated by Django 4.1 on 2022-10-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membermgmt', '0011_alter_comment_criticality_alter_comment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('መስተካከል ያለበት', 'መስተካከል ያለበት'), ('ማይሰራ ነገር', 'ማይሰራ ነገር'), ('አስተያየት', 'አስተያየት'), ('መዳረሻ ገጽ ጭማሪ ጥያቄ', 'መዳረሻ ገጽ ጭማሪ ጥያቄ'), ('መጨመር ያለበት', 'መጨመር ያለበት')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_class',
            field=models.CharField(choices=[('ሣልሣይ', 'ሣልሣይ'), ('ካልዓይ', 'ካልዓይ'), ('ቀዳማይ', 'ቀዳማይ'), ('ራብዓይ', 'ራብዓይ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('ያላገባ', 'ያላገባ'), ('ያገባ', 'ያገባ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='approval',
            field=models.CharField(choices=[('አልጸደቀም', 'አልጸደቀም'), ('ተጠይቁአል', 'ተጠይቁአል'), ('ጸድቁአል', 'ጸድቁአል')], default='ተጠይቁአል', max_length=50),
        ),
        migrations.AlterField(
            model_name='fekad',
            name='kifl',
            field=models.CharField(blank=True, choices=[('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='dikuna',
            field=models.CharField(blank=True, choices=[('-ቀሲስ', '-ቀሲስ'), ('እጩ ቀሲስ', 'እጩ ቀሲስ'), ('እጩ ዲያቆን', 'እጩ ዲያቆን'), ('-ዲያቆን', '-ዲያቆን')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='kifl',
            field=models.CharField(blank=True, choices=[('የሰንበት ት/ቤቱ ቁጥጥርና ክትትል', 'የሰንበት ት/ቤቱ ቁጥጥርና ክትትል'), ('የመረጃ አደረጃጀትና ትንተና ዘርፍ', 'የመረጃ አደረጃጀትና ትንተና ዘርፍ'), ('መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል', 'መረጃ ጥበብና መዛግብት ድምጸ ወምስል ክፍል'), ('የሒሳብ አስተዳደር ዘርፍ', 'የሒሳብ አስተዳደር ዘርፍ'), ('ትምሕርት ክፍል', 'ትምሕርት ክፍል'), ('ሕጻናት ክፍል', 'ሕጻናት ክፍል'), ('መዝሙር ጣእመ ዜማ ክፍል', 'መዝሙር ጣእመ ዜማ ክፍል'), ('የሰንበት ት/ቤቱ ጸሃፊ', 'የሰንበት ት/ቤቱ ጸሃፊ'), ('የሰንበት ት/ቤቱ ዋና ሰብሳቢ', 'የሰንበት ት/ቤቱ ዋና ሰብሳቢ'), ('የጥናትና ምርምር ዘርፍ', 'የጥናትና ምርምር ዘርፍ'), ('የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ', 'የዕቅድ ዝግጅት አፈጻጸምና ፕሮጀክት ዘርፍ'), ('የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል', 'የሰንበት ት/ቤቱ ስራ አመራር ጉባኤ አባል'), ('ንብረት አስተዳደርና ግዢ ዘርፍ', 'ንብረት አስተዳደርና ግዢ ዘርፍ'), ('ልማት፤ሙያ እና በጎ አድራጎት ክፍል', 'ልማት፤ሙያ እና በጎ አድራጎት ክፍል'), ('የሕዝብ ግንኙነት ዘርፍ', 'የሕዝብ ግንኙነት ዘርፍ'), ('የአባላት ክብካቤና ግንኙነት ክፍል', 'የአባላት ክብካቤና ግንኙነት ክፍል'), ('ስነ-ጥበብ ክፍል', 'ስነ-ጥበብ ክፍል')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('ያላገባ', 'ያላገባ'), ('ያገባ', 'ያገባ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('ምግብ ነክ ቁሶች', 'ምግብ ነክ ቁሶች'), ('የቢሮ እቃዎች', 'የቢሮ እቃዎች'), ('ንዋየ ቅድሳት', 'ንዋየ ቅድሳት'), ('የጽህፈት መሳሪያቆች', 'የጽህፈት መሳሪያቆች'), ('የድግስ እቃዎች', 'የድግስ እቃዎች'), ('የኤሌክትሮኒክስ የአይቲ እቃዎች', 'የኤሌክትሮኒክስ/የአይቲ እቃዎች')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('አሮጌ', 'አሮጌ'), ('አዲስ', 'አዲስ'), ('ያገለገለ', 'ያገለገለ'), ('የሚወገድ', 'የሚወገድ')], max_length=100, null=True),
        ),
    ]
